sudo: false
language: node_js

notifications:
  email: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - /\d+\.\d+(\.\d+)?(-\S*)?$/

matrix:
  fast_finish: true

node_js:
  - '10'
  - '8'
  - '6'

os:
  - linux
  - osx

install:
  - npm install
  - ./node_modules/.bin/lerna bootstrap

script:
  - node --version && npm --version
  - npm run ci
