build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

cache:
  - node_modules

branches:
  only:
    - master
    - /\d+\.\d+(\.\d+)?(-\S*)?$/

matrix:
  fast_finish: true

environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "8"
    - nodejs_version: "6"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - ./node_modules/.bin/lerna bootstrap

test_script:
  - node --version && npm --version
  - npm run build
