# Unfortunately, VSTS does not currently support anchors in the YAML files.
# This promote duplication of matrices in strategies.

trigger:
  branches:
    include:
      - master
      - releases/*

jobs:
  - job: Windows
    strategy:
      matrix:
        (Node.js 8): { node_version: 8.x }
        (Node.js 10): { node_version: 10.x }
        (Node.js 12): { node_version: 12.x }
        (Node.js 14): { node_version: 14.x }
    pool:
      vmImage: 'windows-latest'
    steps:
      - template: build-steps.yml
        parameters:
          node_version: $(node_version)

  - job: Linux
    strategy:
      matrix:
        (Node.js 8): { node_version: 8.x }
        (Node.js 10): { node_version: 10.x }
        (Node.js 12): { node_version: 12.x }
        (Node.js 14): { node_version: 14.x }
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: build-steps.yml
        parameters:
          node_version: $(node_version)

  - job: macOS
    strategy:
      matrix:
        (Node.js 8): { node_version: 8.x }
        (Node.js 10): { node_version: 10.x }
        (Node.js 12): { node_version: 12.x }
        (Node.js 14): { node_version: 14.x }
    pool:
      vmImage: 'macOS-latest'
    steps:
      - template: build-steps.yml
        parameters:
          node_version: $(node_version)
